# 02 — Data Understanding  
## AdventureWorks | Inventarios como portafolio de capital

Objetivo: auditar la disponibilidad y calidad de datos para responder:

1) ¿Dónde está el capital en inventarios (por SKU)?  
2) ¿Qué tan rápido rota (por SKU)?  
3) ¿Qué retorno económico genera (por SKU)?  

Esta fase NO modela. Solo confirma:
- tablas disponibles
- campos clave
- llaves
- cobertura temporal
- riesgos y limitaciones

In [1]:
import pandas as pd
import sqlalchemy
import pyodbc

pd.__version__

'2.3.3'

In [2]:
import pandas as pd
from sqlalchemy import create_engine

conn_str = (
    "mssql+pyodbc://sa:StrongPass123!@localhost:1433/"
    "AdventureWorks2019?"
    "driver=ODBC+Driver+18+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

engine = create_engine(conn_str)

In [3]:
tables = pd.read_sql("""
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME
""", engine)

tables

      TABLE_SCHEMA                      TABLE_NAME
0              dbo                  AWBuildVersion
1              dbo                     DatabaseLog
2              dbo                        ErrorLog
3   HumanResources                      Department
4   HumanResources                        Employee
..             ...                             ...
86           Sales                    vSalesPerson
87           Sales  vSalesPersonSalesByFiscalYears
88           Sales             vStoreWithAddresses
89           Sales              vStoreWithContacts
90           Sales          vStoreWithDemographics

[91 rows x 2 columns]

In [4]:
product_sample = pd.read_sql("""
SELECT TOP 10 *
FROM Production.Product
""", engine)

product_sample

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
0,1,Adjustable Race,AR-5381,False,False,None,1000,750,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
1,2,Bearing Ball,BA-8327,False,False,None,1000,750,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,58AE3C20-4F3A-4749-A7D4-D568806CC537,2014-02-08 10:01:36.827
2,3,BB Ball Bearing,BE-2349,True,False,None,800,600,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,9C21AED2-5BFA-4F18-BCB8-F11638DC2E4E,2014-02-08 10:01:36.827
3,4,Headset Ball Bearings,BE-2908,False,False,None,800,600,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,ECFED6CB-51FF-49B5-B06C-7D8AC834DB8B,2014-02-08 10:01:36.827
4,316,Blade,BL-2036,True,False,None,800,600,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,E73E9750-603B-4131-89F5-3DD15ED5FF80,2014-02-08 10:01:36.827
5,317,LL Crankarm,CA-5965,False,False,Black,500,375,0.0,0.0,...,None,L,None,None,None,2008-04-30,None,None,3C9D10B7-A6B2-4774-9963-C19DCEE72FEA,2014-02-08 10:01:36.827
6,318,ML Crankarm,CA-6738,False,False,Black,500,375,0.0,0.0,...,None,M,None,None,None,2008-04-30,None,None,EABB9A92-FA07-4EAB-8955-F0517B4A4CA7,2014-02-08 10:01:36.827
7,319,HL Crankarm,CA-7457,False,False,Black,500,375,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,7D3FD384-4F29-484B-86FA-4206E276FE58,2014-02-08 10:01:36.827
8,320,Chainring Bolts,CB-2903,False,False,Silver,1000,750,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,7BE38E48-B7D6-4486-888E-F53C26735101,2014-02-08 10:01:36.827
9,321,Chainring Nut,CN-6137,False,False,Silver,1000,750,0.0,0.0,...,None,None,None,None,None,2008-04-30,None,None,3314B1D7-EF69-4431-B6DD-DC75268BD5DF,2014-02-08 10:01:36.827

In [5]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Production.Product
""", engine)

   rows
0   504

In [6]:
product_inventory = pd.read_sql("""
SELECT TOP 10 *
FROM Production.ProductInventory
""", engine)

product_inventory

,ProductID,LocationID,Shelf,Bin,Quantity,rowguid,ModifiedDate
0,1,1,A,1,408,47A24246-6C43-48EB-968F-025738A8A410,2014-08-08
1,1,6,B,5,324,D4544D7D-CAF5-46B3-AB22-5718DCC26B5E,2014-08-08
2,1,50,A,5,353,BFF7DC60-96A8-43CA-81A7-D6D2ED3000A8,2014-08-08
3,2,1,A,2,427,F407C07A-CA14-4684-A02C-608BD00C2233,2014-08-08
4,2,6,B,1,318,CA1FF2F4-48FB-4960-8D92-3940B633E4C1,2014-08-08
5,2,50,A,6,364,D38CFBEE-6347-47B1-B033-0E278CCA03E2,2014-08-08
6,3,1,A,7,585,E18A519B-FB5E-4051-874C-58CD58436C95,2008-03-31
7,3,6,B,9,443,3C860C96-15FF-4DF4-91D7-B237FF64480F,2008-03-31
8,3,50,A,10,324,1339E5E3-1F8E-4B82-A447-A8666A264F0C,2008-03-31
9,4,1,A,6,512,6BEAF0A0-971A-4CE1-96FE-692807D5DC00,2014-08-08

In [7]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Production.ProductInventory
""", engine)

   rows
0  1069

In [8]:
product_cost = pd.read_sql("""
SELECT TOP 10 *
FROM Production.ProductCostHistory
""", engine)

product_cost

   ProductID  StartDate    EndDate  StandardCost ModifiedDate
0        707 2011-05-31 2012-05-29       12.0278   2012-05-29
1        707 2012-05-30 2013-05-29       13.8782   2013-05-29
2        707 2013-05-30        NaT       13.0863   2013-05-16
3        708 2011-05-31 2012-05-29       12.0278   2012-05-29
4        708 2012-05-30 2013-05-29       13.8782   2013-05-29
5        708 2013-05-30        NaT       13.0863   2013-05-16
6        709 2011-05-31 2012-05-29        3.3963   2012-05-29
7        710 2011-05-31 2012-05-29        3.3963   2012-05-29
8        711 2011-05-31 2012-05-29       12.0278   2012-05-29
9        711 2012-05-30 2013-05-29       13.8782   2013-05-29

In [9]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Production.ProductCostHistory
""", engine)

   rows
0   395

In [10]:
transaction_history = pd.read_sql("""
SELECT TOP 10 *
FROM Production.TransactionHistory
""", engine)

transaction_history

,TransactionID,ProductID,ReferenceOrderID,ReferenceOrderLineID,TransactionDate,TransactionType,Quantity,ActualCost,ModifiedDate
0,100000,784,41590,0,2013-07-31,W,2,0.0,2013-07-31
1,100001,794,41591,0,2013-07-31,W,1,0.0,2013-07-31
2,100002,797,41592,0,2013-07-31,W,1,0.0,2013-07-31
3,100003,798,41593,0,2013-07-31,W,1,0.0,2013-07-31
4,100004,799,41594,0,2013-07-31,W,1,0.0,2013-07-31
5,100005,800,41595,0,2013-07-31,W,1,0.0,2013-07-31
6,100006,801,41596,0,2013-07-31,W,1,0.0,2013-07-31
7,100007,954,41597,0,2013-07-31,W,1,0.0,2013-07-31
8,100008,955,41598,0,2013-07-31,W,1,0.0,2013-07-31
9,100009,966,41599,0,2013-07-31,W,1,0.0,2013-07-31

In [11]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Production.TransactionHistory
""", engine)

     rows
0  113443

In [12]:
sales_header = pd.read_sql("""
SELECT TOP 10 *
FROM Sales.SalesOrderHeader
""", engine)

sales_header

,SalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,OnlineOrderFlag,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,...,CreditCardID,CreditCardApprovalCode,CurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment,rowguid,ModifiedDate
0,43659,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43659,PO522145787,10-4020-000676,...,16281,105041Vi84182,NaN,20565.6206,1971.5149,616.0984,23153.2339,None,79B65321-39CA-4115-9CBA-8FE0903E12E6,2011-06-07
1,43660,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43660,PO18850127500,10-4020-000117,...,5618,115213Vi29411,NaN,1294.2529,124.2483,38.8276,1457.3288,None,738DC42D-D03B-48A1-9822-F95A67EA7389,2011-06-07
2,43661,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43661,PO18473189620,10-4020-000442,...,1346,85274Vi6854,4.0,32726.4786,3153.7696,985.5530,36865.8012,None,D91B9131-18A4-4A11-BC3A-90B6F53E9D74,2011-06-07
3,43662,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43662,PO18444174044,10-4020-000227,...,10456,125295Vi53935,4.0,28832.5289,2775.1646,867.2389,32474.9324,None,4A1ECFC0-CC3A-4740-B028-1C50BB48711C,2011-06-07
4,43663,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43663,PO18009186470,10-4020-000510,...,4322,45303Vi22691,NaN,419.4589,40.2681,12.5838,472.3108,None,9B1E7A40-6AE0-4AD3-811C-A64951857C4B,2011-06-07
5,43664,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43664,PO16617121983,10-4020-000397,...,806,95555Vi4081,NaN,24432.6088,2344.9921,732.8100,27510.4109,None,22A8A5DA-8C22-42AD-9241-839489B6EF0D,2011-06-07
6,43665,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43665,PO16588191572,10-4020-000146,...,15232,35568Vi78804,NaN,14352.7713,1375.9427,429.9821,16158.6961,None,5602C304-853C-43D7-9E79-76E320D476CF,2011-06-07
7,43666,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43666,PO16008173883,10-4020-000511,...,13349,105623Vi69217,NaN,5056.4896,486.3747,151.9921,5694.8564,None,E2A90057-1366-4487-8A7E-8085845FF770,2011-06-07
8,43667,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43667,PO15428132599,10-4020-000646,...,10370,55680Vi53503,NaN,6107.0820,586.1203,183.1626,6876.3649,None,86D5237D-432D-4B21-8ABC-671942F5789D,2011-06-07
9,43668,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43668,PO14732180295,10-4020-000514,...,1566,85817Vi8045,4.0,35944.1562,3461.7654,1081.8017,40487.7233,None,281CC355-D538-494E-9B44-461B36A826C6,2011-06-07

In [13]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Sales.SalesOrderHeader
""", engine)

    rows
0  31465

In [14]:
sales_detail = pd.read_sql("""
SELECT TOP 10 *
FROM Sales.SalesOrderDetail
""", engine)

sales_detail

,SalesOrderID,SalesOrderDetailID,CarrierTrackingNumber,OrderQty,ProductID,SpecialOfferID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate
0,43659,1,4911-403C-98,1,776,1,2024.9940,0.0,2024.9940,B207C96D-D9E6-402B-8470-2CC176C42283,2011-05-31
1,43659,2,4911-403C-98,3,777,1,2024.9940,0.0,6074.9820,7ABB600D-1E77-41BE-9FE5-B9142CFC08FA,2011-05-31
2,43659,3,4911-403C-98,1,778,1,2024.9940,0.0,2024.9940,475CF8C6-49F6-486E-B0AD-AFC6A50CDD2F,2011-05-31
3,43659,4,4911-403C-98,1,771,1,2039.9940,0.0,2039.9940,04C4DE91-5815-45D6-8670-F462719FBCE3,2011-05-31
4,43659,5,4911-403C-98,1,772,1,2039.9940,0.0,2039.9940,5A74C7D2-E641-438E-A7AC-37BF23280301,2011-05-31
5,43659,6,4911-403C-98,2,773,1,2039.9940,0.0,4079.9880,CE472532-A4C0-45BA-816E-EEFD3FD848B3,2011-05-31
6,43659,7,4911-403C-98,1,774,1,2039.9940,0.0,2039.9940,80667840-F962-4EE3-96E0-AECA108E0D4F,2011-05-31
7,43659,8,4911-403C-98,3,714,1,28.8404,0.0,86.5212,E9D54907-E7B7-4969-80D9-76BA69F8A836,2011-05-31
8,43659,9,4911-403C-98,1,716,1,28.8404,0.0,28.8404,AA542630-BDCD-4CE5-89A0-C1BF82747725,2011-05-31
9,43659,10,4911-403C-98,6,709,1,5.7000,0.0,34.2000,AC769034-3C2F-495C-A5A7-3B71CDB25D4E,2011-05-31

In [15]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Sales.SalesOrderDetail
""", engine)

     rows
0  121317

In [16]:
customer = pd.read_sql("""
SELECT TOP 10 *
FROM Sales.Customer
""", engine)

customer

,CustomerID,PersonID,StoreID,TerritoryID,AccountNumber,rowguid,ModifiedDate
0,1,None,934,1,AW00000001,3F5AE95E-B87D-4AED-95B4-C3797AFCB74F,2014-09-12 11:15:07.263
1,2,None,1028,1,AW00000002,E552F657-A9AF-4A7D-A645-C429D6E02491,2014-09-12 11:15:07.263
2,3,None,642,4,AW00000003,130774B1-DB21-4EF3-98C8-C104BCD6ED6D,2014-09-12 11:15:07.263
3,4,None,932,4,AW00000004,FF862851-1DAA-4044-BE7C-3E85583C054D,2014-09-12 11:15:07.263
4,5,None,1026,4,AW00000005,83905BDC-6F5E-4F71-B162-C98DA069F38A,2014-09-12 11:15:07.263
5,6,None,644,4,AW00000006,1A92DF88-BFA2-467D-BD54-FCB9E647FDD7,2014-09-12 11:15:07.263
6,7,None,930,1,AW00000007,03E9273E-B193-448E-9823-FE0C44AEED78,2014-09-12 11:15:07.263
7,8,None,1024,5,AW00000008,801368B1-4323-4BFA-8BEA-5B5B1E4BD4A0,2014-09-12 11:15:07.263
8,9,None,620,5,AW00000009,B900BB7F-23C3-481D-80DA-C49A5BD6F772,2014-09-12 11:15:07.263
9,10,None,928,6,AW00000010,CDB6698D-2FF1-4FBA-8F22-60AD1D11DABD,2014-09-12 11:15:07.263

In [17]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Sales.Customer
""", engine)

    rows
0  19820

In [18]:
vendor = pd.read_sql("""
SELECT TOP 10 *
FROM Purchasing.Vendor
""", engine)

vendor

,BusinessEntityID,AccountNumber,Name,CreditRating,PreferredVendorStatus,ActiveFlag,PurchasingWebServiceURL,ModifiedDate
0,1492,AUSTRALI0001,Australia Bike Retailer,1,True,True,None,2011-12-23
1,1494,ALLENSON0001,Allenson Cycles,2,True,True,None,2011-04-25
2,1496,ADVANCED0001,Advanced Bicycles,1,True,True,None,2011-04-25
3,1498,TRIKES0001,"Trikes, Inc.",2,True,True,None,2012-02-03
4,1500,MORGANB0001,Morgan Bike Accessories,1,True,True,None,2012-02-02
5,1502,CYCLING0001,Cycling Master,1,True,True,None,2011-12-24
6,1504,CHICAGO0002,Chicago Rent-All,2,True,True,None,2011-12-24
7,1506,GREENWOO0001,Greenwood Athletic Company,1,True,True,None,2012-01-25
8,1508,COMPETE0001,"Compete Enterprises, Inc",1,True,True,None,2011-12-24
9,1510,INTERNAT0001,International,1,True,True,None,2012-01-25

In [19]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Purchasing.Vendor
""", engine)

   rows
0   104

In [20]:
po_header = pd.read_sql("""
SELECT TOP 10 *
FROM Purchasing.PurchaseOrderHeader
""", engine)

po_header

,PurchaseOrderID,RevisionNumber,Status,EmployeeID,VendorID,ShipMethodID,OrderDate,ShipDate,SubTotal,TaxAmt,Freight,TotalDue,ModifiedDate
0,1,4,4,258,1580,3,2011-04-16,2011-04-25,201.0400,16.0832,5.0260,222.1492,2011-04-25
1,2,4,1,254,1496,5,2011-04-16,2011-04-25,272.1015,21.7681,6.8025,300.6721,2011-04-25
2,3,4,4,257,1494,2,2011-04-16,2011-04-25,8847.3000,707.7840,221.1825,9776.2665,2011-04-25
3,4,4,3,261,1650,5,2011-04-16,2011-04-25,171.0765,13.6861,4.2769,189.0395,2011-04-25
4,5,4,4,251,1654,4,2011-04-30,2011-05-09,20397.3000,1631.7840,509.9325,22539.0165,2011-05-09
5,6,4,4,253,1664,3,2011-04-30,2011-05-09,14628.0750,1170.2460,365.7019,16164.0229,2011-05-09
6,7,4,4,255,1678,3,2011-04-30,2011-05-09,58685.5500,4694.8440,1467.1388,64847.5328,2011-05-09
7,8,4,4,256,1616,5,2011-04-30,2011-05-09,693.3780,55.4702,17.3345,766.1827,2011-05-09
8,9,5,4,259,1492,5,2011-12-14,2011-12-23,694.1655,55.5332,17.3541,767.0528,2011-12-23
9,10,4,4,250,1602,5,2011-12-14,2011-12-23,1796.0355,143.6828,44.9009,1984.6192,2011-12-23

In [21]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Purchasing.PurchaseOrderHeader
""", engine)

   rows
0  4012

In [22]:
po_detail = pd.read_sql("""
SELECT TOP 10 *
FROM Purchasing.PurchaseOrderDetail
""", engine)

po_detail

,PurchaseOrderID,PurchaseOrderDetailID,DueDate,OrderQty,ProductID,UnitPrice,LineTotal,ReceivedQty,RejectedQty,StockedQty,ModifiedDate
0,1,1,2011-04-30,4,1,50.2600,201.0400,3.0,0.0,3.0,2011-04-23
1,2,2,2011-04-30,3,359,45.1200,135.3600,3.0,0.0,3.0,2011-04-23
2,2,3,2011-04-30,3,360,45.5805,136.7415,3.0,0.0,3.0,2011-04-23
3,3,4,2011-04-30,550,530,16.0860,8847.3000,550.0,0.0,550.0,2011-04-23
4,4,5,2011-04-30,3,4,57.0255,171.0765,2.0,1.0,1.0,2011-04-23
5,5,6,2011-05-14,550,512,37.0860,20397.3000,550.0,0.0,550.0,2011-05-07
6,6,7,2011-05-14,550,513,26.5965,14628.0750,468.0,0.0,468.0,2011-05-07
7,7,8,2011-05-14,550,317,27.0585,14882.1750,550.0,0.0,550.0,2011-05-07
8,7,9,2011-05-14,550,318,33.5790,18468.4500,550.0,0.0,550.0,2011-05-07
9,7,10,2011-05-14,550,319,46.0635,25334.9250,550.0,0.0,550.0,2011-05-07

In [23]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Purchasing.PurchaseOrderDetail
""", engine)

   rows
0  8845

In [24]:
category = pd.read_sql("""
SELECT TOP 10
    ProductCategoryID,
    Name
FROM Production.ProductCategory
ORDER BY ProductCategoryID
""", engine)

category

   ProductCategoryID         Name
0                  1        Bikes
1                  2   Components
2                  3     Clothing
3                  4  Accessories

In [25]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Production.ProductCategory
""", engine)

   rows
0     4

In [26]:
subcategory = pd.read_sql("""
SELECT TOP 10
    ProductSubcategoryID,
    ProductCategoryID,
    Name
FROM Production.ProductSubcategory
ORDER BY ProductSubcategoryID
""", engine)

subcategory

   ProductSubcategoryID  ProductCategoryID             Name
0                     1                  1   Mountain Bikes
1                     2                  1       Road Bikes
2                     3                  1    Touring Bikes
3                     4                  2       Handlebars
4                     5                  2  Bottom Brackets
5                     6                  2           Brakes
6                     7                  2           Chains
7                     8                  2        Cranksets
8                     9                  2      Derailleurs
9                    10                  2            Forks

In [27]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM Production.ProductSubcategory
""", engine)

   rows
0    37