In [1]:
SNAPSHOT_DATE = "2026-02-01"
DAYS_IN_PERIOD = 365

In [2]:
import pandas as pd
import numpy as np

In [3]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://sa:StrongPass123!@localhost:1433/AdventureWorks2019"
    "?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"
)

In [4]:
pd.read_sql("SELECT TOP 5 name FROM sys.tables", engine)

               name
0      SalesTaxRate
1  PersonCreditCard
2       PersonPhone
3    SalesTerritory
4   PhoneNumberType

In [5]:
sku_master = pd.read_sql("""
SELECT
    p.ProductID            AS sku_id,
    p.Name                 AS sku_name,
    c.Name                 AS category_name,
    sc.Name                AS subcategory_name
FROM Production.Product p
LEFT JOIN Production.ProductSubcategory sc
    ON p.ProductSubcategoryID = sc.ProductSubcategoryID
LEFT JOIN Production.ProductCategory c
    ON sc.ProductCategoryID = c.ProductCategoryID
""", engine)

sku_master.head()

   sku_id               sku_name category_name subcategory_name
0       1        Adjustable Race          None             None
1       2           Bearing Ball          None             None
2       3        BB Ball Bearing          None             None
3       4  Headset Ball Bearings          None             None
4     316                  Blade          None             None

In [6]:
inventory = pd.read_sql("""
SELECT
    ProductID AS sku_id,
    SUM(Quantity) AS inventory_units
FROM Production.ProductInventory
GROUP BY ProductID
""", engine)

inventory.head()

   sku_id  inventory_units
0       1             1085
1       2             1109
2       3             1352
3       4             1322
4     316             1361

In [7]:
inventory.shape

(432, 2)

In [8]:
unit_cost = pd.read_sql("""
WITH latest_cost AS (
    SELECT
        ProductID,
        StandardCost,
        ROW_NUMBER() OVER (
            PARTITION BY ProductID
            ORDER BY StartDate DESC
        ) AS rn
    FROM Production.ProductCostHistory
)
SELECT
    ProductID AS sku_id,
    StandardCost AS unit_cost
FROM latest_cost
WHERE rn = 1
""", engine)

unit_cost.head()

   sku_id  unit_cost
0     707    13.0863
1     708    13.0863
2     709     3.3963
3     710     3.3963
4     711    13.0863

In [9]:
unit_cost.describe()

           sku_id    unit_cost
count  293.000000   293.000000
mean   853.000000   433.980828
std     84.726029   534.240410
min    707.000000     0.856500
25%    780.000000    35.959600
50%    853.000000   199.851900
75%    926.000000   601.743700
max    999.000000  2171.294200

In [10]:
sales_12m = pd.read_sql("""
SELECT
    sod.ProductID AS sku_id,
    SUM(sod.OrderQty) AS units_sold_12m,
    SUM(sod.LineTotal) AS sales_12m
FROM Sales.SalesOrderDetail sod
JOIN Sales.SalesOrderHeader soh
    ON sod.SalesOrderID = soh.SalesOrderID
WHERE soh.OrderDate >= DATEADD(DAY, -365, GETDATE())
GROUP BY sod.ProductID
""", engine)

sales_12m.head()

Empty DataFrame
Columns: [sku_id, units_sold_12m, sales_12m]
Index: []

In [11]:
sales_12m.describe()

       sku_id units_sold_12m sales_12m
count       0              0         0
unique      0              0         0
top       NaN            NaN       NaN
freq      NaN            NaN       NaN

In [12]:
inventory_gold = (
    sku_master
    .merge(inventory, on="sku_id", how="left")
    .merge(unit_cost, on="sku_id", how="left")
    .merge(sales_12m, on="sku_id", how="left")
)

In [13]:
inventory_gold = inventory_gold.fillna({
    "inventory_units": 0,
    "units_sold_12m": 0,
    "sales_12m": 0
})

/var/folders/ry/4019pgsd4073m3w_k8vm8bqr0000gn/T/ipykernel_24080/4288047452.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  inventory_gold = inventory_gold.fillna({

In [14]:
inventory_gold.head()

,sku_id,sku_name,category_name,subcategory_name,inventory_units,unit_cost,units_sold_12m,sales_12m
0,1,Adjustable Race,None,None,1085.0,NaN,0,0
1,2,Bearing Ball,None,None,1109.0,NaN,0,0
2,3,BB Ball Bearing,None,None,1352.0,NaN,0,0
3,4,Headset Ball Bearings,None,None,1322.0,NaN,0,0
4,316,Blade,None,None,1361.0,NaN,0,0

In [15]:
DAYS_IN_PERIOD = 365

inventory_gold["inventory_value"] = (
    inventory_gold["inventory_units"] * inventory_gold["unit_cost"]
)

inventory_gold["inventory_turnover"] = (
    inventory_gold["sales_12m"] / inventory_gold["inventory_value"]
).replace([np.inf, -np.inf], 0)

inventory_gold["days_inventory"] = (
    DAYS_IN_PERIOD / inventory_gold["inventory_turnover"]
).replace([np.inf, -np.inf], 0)

In [16]:
inventory_gold.sort_values("inventory_value", ascending=False).head(10)

,sku_id,sku_name,category_name,subcategory_name,inventory_units,unit_cost,units_sold_12m,sales_12m,inventory_value,inventory_turnover,days_inventory
251,747,"HL Mountain Frame - Black, 38",Components,Mountain Frames,834.0,739.0410,0,0,616360.1940,0.0,0.0
252,748,"HL Mountain Frame - Silver, 38",Components,Mountain Frames,738.0,747.2002,0,0,551433.7476,0.0,0.0
254,750,"Road-150 Red, 44",Bikes,Road Bikes,223.0,2171.2942,0,0,484198.6066,0.0,0.0
280,776,"Mountain-100 Black, 42",Bikes,Mountain Bikes,194.0,1898.0944,0,0,368230.3136,0.0,0.0
257,753,"Road-150 Red, 56",Bikes,Road Bikes,163.0,2171.2942,0,0,353920.9546,0.0,0.0
296,792,"Road-250 Red, 58",Bikes,Road Bikes,227.0,1554.9479,0,0,352973.1733,0.0,0.0
278,774,"Mountain-100 Silver, 48",Bikes,Mountain Bikes,164.0,1912.1544,0,0,313593.3216,0.0,0.0
255,751,"Road-150 Red, 48",Bikes,Road Bikes,140.0,2171.2942,0,0,303981.1880,0.0,0.0
277,773,"Mountain-100 Silver, 44",Bikes,Mountain Bikes,158.0,1912.1544,0,0,302120.3952,0.0,0.0
279,775,"Mountain-100 Black, 38",Bikes,Mountain Bikes,155.0,1898.0944,0,0,294204.6320,0.0,0.0

In [17]:
SNAPSHOT_DATE = "2026-02-01"
inventory_gold["snapshot_date"] = SNAPSHOT_DATE

In [18]:
from pathlib import Path

Path("data/gold").mkdir(parents=True, exist_ok=True)

In [19]:
inventory_gold.to_parquet(
    f"data/gold/inventory_gold_{SNAPSHOT_DATE}.parquet",
    index=False
)

In [20]:
Path("data/gold").exists()

True

In [21]:
inventory_gold.shape, inventory_gold[["inventory_units","inventory_value","sales_12m","days_inventory"]].describe()

((504, 12),
        inventory_units  inventory_value  sales_12m  days_inventory
 count       504.000000       293.000000      504.0           219.0
 mean        666.615079     65617.180994        0.0             0.0
 std         597.422152     99162.505237        0.0             0.0
 min           0.000000         0.000000        0.0             0.0
 25%         144.000000         0.000000        0.0             0.0
 50%         607.000000     13976.976000        0.0             0.0
 75%        1029.000000     90904.625600        0.0             0.0
 max        1911.000000    616360.194000        0.0             0.0)

In [22]:
inventory_gold.sort_values("inventory_value", ascending=False).head(15)[
    ["sku_id","sku_name","category_name","subcategory_name","inventory_units","unit_cost","inventory_value","sales_12m","days_inventory"]
]

,sku_id,sku_name,category_name,subcategory_name,inventory_units,unit_cost,inventory_value,sales_12m,days_inventory
251,747,"HL Mountain Frame - Black, 38",Components,Mountain Frames,834.0,739.0410,616360.1940,0,0.0
252,748,"HL Mountain Frame - Silver, 38",Components,Mountain Frames,738.0,747.2002,551433.7476,0,0.0
254,750,"Road-150 Red, 44",Bikes,Road Bikes,223.0,2171.2942,484198.6066,0,0.0
280,776,"Mountain-100 Black, 42",Bikes,Mountain Bikes,194.0,1898.0944,368230.3136,0,0.0
257,753,"Road-150 Red, 56",Bikes,Road Bikes,163.0,2171.2942,353920.9546,0,0.0
296,792,"Road-250 Red, 58",Bikes,Road Bikes,227.0,1554.9479,352973.1733,0,0.0
278,774,"Mountain-100 Silver, 48",Bikes,Mountain Bikes,164.0,1912.1544,313593.3216,0,0.0
255,751,"Road-150 Red, 48",Bikes,Road Bikes,140.0,2171.2942,303981.1880,0,0.0
277,773,"Mountain-100 Silver, 44",Bikes,Mountain Bikes,158.0,1912.1544,302120.3952,0,0.0
279,775,"Mountain-100 Black, 38",Bikes,Mountain Bikes,155.0,1898.0944,294204.6320,0,0.0
276,772,"Mountain-100 Silver, 42",Bikes,Mountain Bikes,153.0,1912.1544,292559.6232,0,0.0
299,795,"Road-250 Black, 52",Bikes,Road Bikes,188.0,1554.9479,292330.2052,0,0.0
282,778,"Mountain-100 Black, 48",Bikes,Mountain Bikes,153.0,1898.0944,290408.4432,0,0.0
253,749,"Road-150 Red, 62",Bikes,Road Bikes,133.0,2171.2942,288782.1286,0,0.0
326,822,"ML Road Frame-W - Yellow, 38",Components,Road Frames,796.0,360.9428,287310.4688,0,0.0